### PR TITLE
specify node version

### PR DESCRIPTION
**Pull request by miyabitanimchi**
There was an error when the code on the develop branch was deployed to Heroku.
スクリーンショット 2022-02-09 午後0 18 38

And it seems like we need to specify Node version, so I specified it on package.json.
Before merging this branch, could you do `yarn install` and run the app, and see if it works without any problems on your local environment?

Thank you!

### CODE REVIEW

**Comment by Kit486759** [comment]
Hi @miyabitanimchi , I got error in both yarn install and run 
image

**Review by Kit486759 — COMMENTED** [review]
Hi @miyabitanimchi , I got error in both yarn install and run 
image

**Comment by miyabitanimchi** [comment]
> Hi @miyabitanimchi , I got error in both yarn install and run image

Thank you so much for checking @Kit486759.
What is your node version in your environment? Perhaps version 12?
You can check with this command `node -v`

**Comment by BlackStone8960** [comment]
It worked without any errors in my environment. I mentioned it in Slack as well, but my node version is v14.18.0.

**Comment by YumiKimbara** [comment]
Screen Shot 2022-02-09 at 9 31 45 PM
I also got the same error as Kit, and my node version is v12.13.1

**Review by BlackStone8960 — APPROVED** [review]

**Pull request merged**
