### PR TITLE
align message box

### PR DESCRIPTION
**Pull request by Kit486759**
Adjust width and space to make send and receive messages clear on both sides.
image

### CODE REVIEW

**Review by miyabitanimchi — COMMENTED** [review]
On my browser they look like this 🤯 But is that another problem? 

messagebox
chatbox

**Comment by Kit486759** [comment]
> On my browser they look like this 🤯 But is that another problem?

Thankyou Miyabi.  That's weird its works well in my environment, I had a little fix on it. Could you please review again?

**Comment by miyabitanimchi** [comment]
@Kit486759 
On my environment this happens when there is message(s) without any white space. This happens on your environment too? 
messagebox2

chatbox2

If all the messages has white space it looks good ↓ 👍
messagebox3
chatbox3

**Comment by Kit486759** [comment]
> 
> If all the messages has white space it looks good ↓ 👍 ![messagebox3](https://user-

Thank you  Miyabi, I have rearrang the style.  Also adjust the width to keep the text box display correctly in both popup message and message page.

**Review by miyabitanimchi — APPROVED** [review]
It looks perfect now! Thank you @Kit486759

**Review by BlackStone8960 — APPROVED** [review]
It looks perfect now, thank you!

**Pull request merged**
