### PR TITLE
Feature max limit of input field

### PR DESCRIPTION
**Pull request by YumiKimbara**
I added the features below.

1. set the max limit of the characters and some validations in each bio, firstname, lastname, email, and phone input on the profile page.

 - First name: 50 characters
 - Last name: 50 characters
 - Email Address: 62 characters
 - Phone number: 15 numbers
 - bio: 1000 characters

2. change the button name from login to confirm in the delete account modal after logging in with the email address.

### CODE REVIEW

**Comment by BlackStone8960** [comment]
Sorry for the trouble, but can you merge develop branch to this branch first if you have time? Because I can't go to profile editing page because the structure of database has been changed. 
You need to check many files to merge it, so if you don't know how to solve conflict, please let me know.

**Comment by YumiKimbara** [comment]
I merged develop branch to feature-maxLimitOfInputField. Could you check it again? Thank you!

**Comment by BlackStone8960** [comment]
It seems it hasn't been merged. Can you check it if you pushed your merged result or not? 
Also, can you set max limit of input field to sign up page too?

Sorry for bothering you!

**Comment by YumiKimbara** [comment]
I added the same functionality to the signup page.
Also, I changed the phone input type from 'number' to 'text' and allowed typing only numbers in this input.

**Review by BlackStone8960 — DISMISSED** [review]
It worked correctly, thank you for doing such a great job!

**Review by BlackStone8960 — APPROVED** [review]
Thank you for merging!

**Pull request merged**
