### PR TITLE
Feature video

### PR DESCRIPTION
**Pull request by Kit486759**
Embed youtube video in top page.
*Autoplay disabled due to google policy.

### CODE REVIEW

**Review by miyabitanimchi — APPROVED** [review]
Thank you for your great job. It looks good!
About the end of the video though, now it also shows other related or recommended videos.
It seems like if we add `?rel=0` too the end of the url,  it can only show other Alex's videos.
I think just showing his videos is better, but could you talk to Alex about this specification when you have time?

(If my research is correct, we need to pay for plugin to remove all the related videos)

**Comment by Kit486759** [comment]
> Thank you for your great job. It looks good! About the end of the video though, now it also shows other related or recommended videos. It seems like if we add `?rel=0` too the end of the url, it can only show other Alex's videos. I think just showing his videos is better, but could you talk to Alex about this specification when you have time?
> 
> (If my research is correct, we need to pay for plugin to remove all the related videos)

Thanks Miyabi for the Awesome suggestion!! I have added the rel params and its just showing the video from Alex's channel.
Its much more better.

**Comment by miyabitanimchi** [comment]
> > Thank you for your great job. It looks good! About the end of the video though, now it also shows other related or recommended videos. It seems like if we add `?rel=0` too the end of the url, it can only show other Alex's videos. I think just showing his videos is better, but could you talk to Alex about this specification when you have time?
> > (If my research is correct, we need to pay for plugin to remove all the related videos)
> 
> Thanks Miyabi for the Awesome suggestion!! I have added the rel params and its just showing the video from Alex's channel. Its much more better.

Thank you so much Kit, you can merge this branch to `develop`, and if you haven't talked about this spec with Alex, let's confirm about it with him on the next meeting 👍

**Comment by Kit486759** [comment]
> > > Thank you for your great job. It looks good! About the end of the video though, now it also shows other related or recommended videos. It seems like if we add `?rel=0` too the end of the url, it can only show other Alex's videos. I think just showing his videos is better, but could you talk to Alex about this specification when you have time?
> > > (If my research is correct, we need to pay for plugin to remove all the related videos)
> > 
> > 
> > Thanks Miyabi for the Awesome suggestion!! I have added the rel params and its just showing the video from Alex's channel. Its much more better.
> 
> Thank you so much Kit, you can merge this branch to `develop`, and if you haven't talked about this spec with Alex, let's confirm about it with him on the next meeting 👍

I discuss it with Alex, he suggest to keep auto play in muted. I will change it and merge the code.

**Comment by Kit486759** [comment]
Set show subtitle by default

**Pull request merged**
