### PR TITLE
Feature responsive

### PR DESCRIPTION
**Pull request by Kit486759**
The mobile style for Main, Filter1, Filter2 and User result page.

### CODE REVIEW

**Review by BlackStone8960 — COMMENTED** [review]
Thank you for adding styles. The margin under filter 2 looks pretty large, and the layout of footer looks off, but is this ok with current design?

Screen Shot 2022-01-06 at 3 27 53 PM

**Comment by Kit486759** [comment]
Hi all. I have merge the v2. Please review.

**Comment by Kit486759** [comment]
> Thank you for adding styles. The margin under filter 2 looks pretty large, and the layout of footer looks off, but is this ok with current design?
> 
> Screen Shot 2022-01-06 at 3 27 53 PM

Thanks Taichi. I will fix it.

**Review by miyabitanimchi — COMMENTED** [review]
@Kit486759  Such an amazing job, thank you so much Kit.🙌💪 I have a few things as follows:

1.  I left suggestions below so please check. I thought it would look better it we have a little padding-y on every page (the value should be the same on every page so we can have unified style). But it's just my suggestion so you can still decide with Alex if you'll apply them.

2. For the breakpoint you made, I think it's nice that we create a file called `_mixin.scss` and put in the file in `/src/styles/abstracts`. Probably you already know the way, but in the `_mixin.scss` file, you can write mixin for breakpoint like below:
```
// src/styles/abstracts/_mixin.scss
$mb: 767px;

@mixin mobile {
  @media screen and (max-width: $mb) {
    @content;
  }
}
```

Then, you can import the mixin with `@include` in files that you want to use the breakpoint, like,
```
// any file you want to use the breakpoint
&--metal {
    @include subCatalogButton;
    background: url(/images/edge/sub-catalog-metal.png);
    min-width: 170px;
 @include mobile {
      min-width: 130px;
    }
}
```

For now we are going to have one breakpoint, but the separated file can be useful in the future when we need to add more breakpoints or need to change the current breakpoint. It'll be easy to manage code.

3. If there is no special reason, could you change `max-width: 576px`, to `767px`? (768px is one of common devices and it's a small or medium tablet size, so our app, 〜767px has the mobile version, and 768px〜 has the desktop version for now)

Let me know if you have any questions or something to discuss 👍

**Comment by miyabitanimchi** [comment]
Also when you create `src/styles/abstracts/_mixin.scss`, could you put these mixins in the file too? 

スクリーンショット 2022-01-08 午後10 05 36

**Comment by Kit486759** [comment]
Hi all, I have fixed the code. Please have a look. Thankss!

**Review by miyabitanimchi — COMMENTED** [review]
Thank you so much again for your hard work, but there are some parts we need to fix and improve. Please check my comments below.

1. **Remove margin right on header icons when mobile.** You can check the comment with code below.

2. **Footer layout is still off when mobile.** Alex wants to add a link for his blog on the footer, so there will be more contents. I created a new design for the footer like below but what do you think? You can talk with Alex and make sure what he wants.

current broken footer
スクリーンショット 2022-01-13 午後11 42 06

my suggestion
スクリーンショット 2022-01-13 午後11 33 27

3. **Change all the 576px breakpoints to 767px (import the breakpoint mixin on `_mixin.scss`).** Check `_MusicianPage.scss`, `_header.scss`, `_Chatbox.scss`, `Header.js`, `MusicianPage.js`.


4. **layout on tablets with 768px is off** I don't think we have to make perfect responsive design for all the width, but 768px is one of common breakpoints for small/medium tablets. So it's better we have not broken layout for this

for example on the filter1 page
スクリーンショット 2022-01-13 午後11 55 11

5. Thank you for adding padding. Sorry I should've told you this  but I think it's better to have "Pick a Style" sentence on mobile device too, because users maybe can't know if the category image is able to be swiped and tapped with the current design, but what do you think? Maybe the sentence can be something like "Pick a Style (swipe and tap)" Could you talk to Alex about this too?
スクリーンショット 2022-01-14 午前0 01 40


Sorry for many orders, let me know if you need any help, want to share tasks or have any other suggestions 👍

**Comment by Kit486759** [comment]
Hi @miyabitanimchi  I have fixed the layout.
1,3,4 Fixed.
2. I suggest the layout like this to keep the main box bigger in small device. I also add the place holder for the blog.
image
5. Totally agree with you. added the text to the top.

**Review by miyabitanimchi — APPROVED** [review]
@Kit486759 Hi Kit, thank you so much for improving the layouts and code. Now they look great! And thank you for your suggestion for the footer design. 🙂 You can now merge this branch to `develop`.

**Pull request merged**
