### PR TITLE
Feature responsive create account

### PR DESCRIPTION
**Pull request by YumiKimbara**
I created responsive design for creating acount pages. (these two pages below)
Screen Shot 2022-02-21 at 12 07 19 PM   Screen Shot 2022-02-21 at 12 07 54 PM

### CODE REVIEW

**Review by miyabitanimchi — COMMENTED** [review]
@YumiKimbara Thank you so much for working on this! I 
On my environment, the textarea for Bio on the signup form is not placed in the center, and the best solution to make it better is that we can add className (`.textarea-signup` or something) for the textarea for Bio and add `width: 100%` .
(There could be other ways but it's really possible that other style on other pages will be off)

Please try above when you have time, and let me know how it looks on your environment, thank you!🙏

**Review by Kit486759 — APPROVED** [review]
Hi @YumiKimbara . Its working fine to me. Could you reduce the extra space on bottom, that will be perfect. Thank you!

**Comment by Kit486759** [comment]
Hi @YumiKimbara. I have reduced the extra space. Can you please check?  Thank you!

**Comment by Kit486759** [comment]
@YumiKimbara  I fixed the extra space on desktop view.

**Comment by YumiKimbara** [comment]
@Kit486759 @miyabitanimchi Sorry for being late. I fixed the code based on the comments from you two, and I also deleted the extra space on the bottom, so could you check it again?

**Review by miyabitanimchi — APPROVED** [review]
@YumiKimbara For me I thought it looks good! Thank you so much! 🙌

**Review by Kit486759 — APPROVED** [review]
It's working fine. Thank you!

**Pull request merged**
