### PR TITLE
Feature chat input

### PR DESCRIPTION
**Pull request by Kit486759**
Fixed:
- display maximum 3 lines in input box
- Able to write and read line break by firebase database
- Enter key for line break

### CODE REVIEW

**Comment by BlackStone8960** [comment]
So I meant I want to make it like this. This is the example of WhatsApp, but the input field is expanded as user starts new lines, isn't it?
WhatsApp_make_new_lines

It maybe happens only in my environment, but input field is not expanded enough for now when user starts especially the third line like this gif.
MF_make_new_line

If Alex said it's okay with this style or it's difficult to style it, it's okay though!

**Comment by Kit486759** [comment]
Thank you for feedback @BlackStone8960  yeah, I agree it have to be improve as the example you gave. I will work on it.

**Comment by BlackStone8960** [comment]
Thank you so much Kit, you can do it!

**Comment by Kit486759** [comment]
@BlackStone8960  I have fixed the function by Material Ui. lol
Please have a look.

**Comment by BlackStone8960** [comment]
It has become much better than before! Thank you so much :)

**Pull request merged**
