### PR TITLE
Added the flow to create Stripe Connected Account and Payment flow, fixed problem related to Redux

### PR DESCRIPTION
**Pull request by BlackStone8960**
Enabled producers to create their accounts in Stripe and created payment flow using API.
Also, I fixed some problems related with Redux that will be happened when editing user profile because it's necessary to implement these features.

If you have time, please test these flow. 
I'm setting it as testing environment, so you won't pay real money. Don't worry.

 - **Please use this URL https://musicianfirstcanada-staging.herokuapp.com/ to test payment functionalities** 

 - To create account, you can start it by selecting producer as the occupation when signing up new account, and follow the steps (You don't have to input real information in this flow)
 
 - To test payment, 
1. Choose one producer who has Stripe account (for testing, you can choose your own account where you created Stripe account) 
2. Push "Hire {producer name}" button 
3. Select one of three hiring plans 
4. Input testing card information referencing this page https://stripe.com/docs/testing (e.g. 4242-4242-4242-4242)
5. If it's succeeded, you should proceed to a page that shows Payment successful

Also I edited Redux code related to profile editing, so you can test editing correctly work or not as well if you have time.

Thank you!

### CODE REVIEW

**Review by Kit486759 — DISMISSED** [review]
image
It looks great. Thank you  @BlackStone8960 for the awesome work.

**Review by miyabitanimchi — DISMISSED** [review]
It worked, You are awesome Taichi 🙌
スクリーンショット 2021-11-11 午後0 16 50

**Comment by BlackStone8960** [comment]
Just a small change. Now user don't have to set the same email address at our app and Stripe, so I deleted a warning sentence shown before creating Stripe account.

Screen Shot 2021-11-11 at 1 37 12 PM

**Comment by YumiKimbara** [comment]
I tried the payment system, and it seems good! Thank you :)

**Review by miyabitanimchi — APPROVED** [review]

**Pull request merged**
